### ISSUE TITLE
WoWDatabaseEditor doesnt start issue still persists (for me)

### ISSUE THREAD

**Issue by iFulVius** [BAndysc/WoWDatabaseEditor#197]
**Describe the bug**

- Downloaded the latest build 2021.3
- After that proceeded to go to settings and activate silent updates + auto update
- Restarted the .Exe to make use of the updated version
- Doesnt open up after anymore, Only opens up the Starting window or as named on my PC "TestWindow"
- However the normal 2021.3 build without the updates starts up as normal

**Version (commit hash)**
Please include what was the WoW Database Editor version (commit hash). **If you downloaded binary, open file COMMIT_HASH from the main folder and paste the content in the issue description**

- 2021.3
If you have built the binary yourself, check commit hash with `git rev-parse HEAD`

**To Reproduce**

Stated up above already

**Expected behavior**

**Screenshots**

**Comment by iFulVius** [comment]
a little update, I've gotten myself a completely new System a few days ago and now the DatabaseEditor works just as fine as it should (even on the newest update). Is it possible that the DatabaseEditor stores some sort of data somewhere that makes it not want to start up as it should once it crashed or something like that ?
Greetings.

**Comment by BAndysc** [comment]
Yes, the app might crash if the user settings got corrupted, they are stored in `%appdata%/.../Local/WoWDatabaseEditor`. Recently I've added a command line argument `--console` which will display an error message when such problem occurs.

Since I guess you don't have the access to the old machine, I am gonna close the issue as it is impossible to track down what happened.

And for the future reference if that happens, please use `--console` argument and post the error message.
