### ISSUE TITLE
prebuild pls

### ISSUE THREAD

**Issue by ironhead123** [BAndysc/WoWDatabaseEditor#2]
Hi,
i can´t get it to work. I do NuGet restore but it doesn´t built. I dont know why. Pls make a prebuilt, only to test a little.

thanks!
Greetings Ironhead

**Comment by BAndysc** [comment]
Hello, I have just cloned repo to the new folder, restored nuget packages and everything built file, can you provide build log so that we could fix that? 

Anyway, I have created prebuilt release: https://github.com/BAndysc/WoWDatabaseEditor/releases/tag/v0-prealpha keep in mind it is still in early stages

**Comment by ironhead123** [comment]
Im not at home at the moment. But in one week i send build log.

**Comment by BAndysc** [comment]
If it still happens, please let me know.
