### ISSUE TITLE
A delete from conditions is generated everytime

### ISSUE THREAD

**Issue by CraftedRO** [BAndysc/WoWDatabaseEditor#233]
**Describe the bug**
An annoying delete from conditions is generated every time.

**Version (commit hash)**
in main folder I don't have commit_hash, but it's the latest 2024.1 version.

**To Reproduce**
1. Go to 'wow database editor 2024.1'
2. Click on 'creature script for example'
3. Scroll down to 'Pick a creature with a script let's say Defias Thug ENTRY= 38'
4. Click copy sql then paste it anywhere
5. See: DELETE FROM  `conditions` WHERE `SourceTypeOrReferenceId` = 22 AND `SourceEntry` = 38 AND `SourceId` = 0;

**Expected behavior**
Most likely this delete from  `conditions`  shoud not be generated since we don't have to do with conditions.

**Screenshots**
no need.

**Comment by BAndysc** [comment]
This is intended and I don't see a problem here. Rather than keeping state of previous conditions, I think it is better to just always invoke delete. It is never wrong.

**Comment by CraftedRO** [comment]
I was expecting this answer, well it's annoyng as fk since we don't talk about conditions table/s.

**Comment by CraftedRO** [comment]
as a matter of fact some users are even confused about this and they think this delete condition query is part of the generated change as you can see here: https: //github.com/TrinityCore/TrinityCore/issues/29091#issue-1771637301

**Comment by BAndysc** [comment]
@CraftedRO I have discussed this with the team, and we agreed there is nothing wrong with the DELETE FROM conditions query.

> They think this delete condition query is part of the generated change

Conditions **are** an integral part of SmartScripts. Keep in mind, even if the new script doesn't have any conditions, there could still be some conditions from an old version of the script. Hence, it is safer to always include the delete.

Remember, different rules apply to SQL updates than for the code. The code is constantly modified, unlike SQL updates, which are NEVER changed after being pushed. That's why it is important not to bloat the C++ code with unnecessary lines and this rule doesn't straightforwardly apply to the SQL. In fact, without this DELETE, to do a proper fix review, the reviewer would have to check the current database content to ensure there are no old conditions (or trust the author, but this is also not always the best solution, right?).

Additionally, when reviewing an SQL fix, it is better when all the repetitive queries (like delete + insert to SmartScripts) **always** follow the same rule: "delete for a single entry, then insert for this single entry, then delete and insert conditions." This refers more to @ghost's suggestions to merge all SmartScript inserts into a single insert. It is not a good idea. There are no rewards for compact queries.

**Comment by CraftedRO** [comment]
I personally woud prefer to check myself "IF" I have to modify related condition rather than have to remove this non-sense auto-generated query on every generated change I do on creature script or others, and yes I said non-sense because I don't wanna delete the related conditions because that's most of the times it's not the case to do so, moreover If I'm not wrong when user press run, it will execute this query too without having the posibility to remove it so this will result in users having maybe good conditions removed from database by mistake...

**Comment by BAndysc** [comment]
Em, I am feeling there is some misunderstanding what this query and/or editor does.

Let's take a look at 27811 SAI:
<img width="810" alt="image" src="https://github.com/BAndysc/WoWDatabaseEditor/assets/5689666/28e7d568-b14c-40da-8e17-5572c97ba29d">

Four SAI actions, two events - they depend on a condition. Depending on the are the npc is spawned in, it invokes different actions.

So upon loading, you instantly see there are some conditions related to this script. When you export the script, it exports the script and conditions:

```
 -- Brew Vendor smart ai
SET @ENTRY := 27811;
UPDATE `creature_template` SET `AIName` = 'SmartAI', `ScriptName` = '' WHERE `entry` = @ENTRY;
DELETE FROM `smart_scripts` WHERE `source_type` = 0 AND `entryOrGuid` = @ENTRY;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `Difficulties`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(@ENTRY, 0, 0, 1, '', 11, 0, 100, 0, 0, 0, 0, 0, 2, 774, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On respawn - Self: Set faction to Escortee (774)'),
(@ENTRY, 0, 1, 0, '', 61, 0, 100, 0, 0, 0, 0, 0, 11, 49672, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On respawn - Self: Cast spell  BOTM - Vendor - Transform -  Alliance (49672) on Self'),
(@ENTRY, 0, 2, 3, '', 11, 0, 100, 0, 0, 0, 0, 0, 2, 775, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On respawn - Self: Set faction to Escortee (775)'),
(@ENTRY, 0, 3, 0, '', 61, 0, 100, 0, 0, 0, 0, 0, 11, 49673, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On respawn - Self: Cast spell  BOTM - Vendor - Transform -  Horde (49673) on Self');

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 22 AND `SourceEntry` = 27811 AND `SourceId` = 0;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `ConditionStringValue1`, `NegativeCondition`, `Comment`) VALUES 
(22, 1, 27811, 0, 0, 23, 1, 1537, 0, 0, '', 0, 'Object in area Ironforge (1537)'),
(22, 3, 27811, 0, 0, 23, 1, 1637, 0, 0, '', 0, 'Object in area Orgrimmar (1637)');
```

Because that's ultimately related. The DELETE is essential, if I add a new event as the very first event, i.e.
<img width="810" alt="image" src="https://github.com/BAndysc/WoWDatabaseEditor/assets/5689666/21cdf092-aac0-414d-8b4e-9ea815cc834f">

The conditions change their `SourceGroup`, as this is the `id` of the sai line:

```
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 22 AND `SourceEntry` = 27811 AND `SourceId` = 0;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `ConditionStringValue1`, `NegativeCondition`, `Comment`) VALUES 
(22, 2, 27811, 0, 0, 23, 1, 1537, 0, 0, '', 0, 'Object in area Ironforge (1537)'),
(22, 4, 27811, 0, 0, 23, 1, 1637, 0, 0, '', 0, 'Object in area Orgrimmar (1637)');
```

Long story short: when you load an existing script, you can instantly see if the script has conditions or not. Even if you don't see it, it will be exported just fine.

**What is more!** Let's load 17233 SAI. It is empty in the latest TC master. Let's add some SAI without `DELETE FROM conditions` (i.e. you edit the SAI manually).
<img width="883" alt="image" src="https://github.com/BAndysc/WoWDatabaseEditor/assets/5689666/b5557e0c-a38c-4e3a-8c8e-da951ac2cf42">

You save the script, restart the server and the npc is not talking. Why? Apparently there were some leftovers in `conditions` table! It is obvious after reloading the script in the editor:

<img width="883" alt="image" src="https://github.com/BAndysc/WoWDatabaseEditor/assets/5689666/9f114568-1da6-4404-bbea-252e50800e91">

The condition needs to be deleted. 

So there is no way to remove good conditions by mistake.

**Comment by CraftedRO** [comment]
> Long story short: when you load an existing script, you can instantly see if the script has conditions or not. Even if you don't see it, it will be exported just fine.

But if it doesn't have, woudn't be "smart" not to generate that query line at all ?

**Comment by BAndysc** [comment]
> But if it doesn't have, woudn't be "smart" not to generate that query line at all ?

Yes, there are cases when it is not needed, but again, I, nor the team, don't see any problem in having it: removing this line doesn't add any value to a PR/fix. If anything, it adds some value, see the reasons posted before (tl;dr it standardizes queries). Again, SQL updates are not code. There is no point making it as short as possible, there is more value when all queries look similar.

**Comment by BAndysc** [comment]
Plus I can see more mistakes when this line is generated conditionally. I.e. an user generates a query, there is DELETE FROM conditions, because there were some conditions, then they work on the script for a couple more days, finally they export the final script, but at this point there is no DELETE FROM conditions, because their local db no longer has conditions and the user forgets he had to include DELETE in the PR/fix.
